"""Generate pytest regression tests for confirmed access-control findings.

Each generated test encodes the *secure* expectation: a non-owner identity must not
be able to retrieve the owner's private object. Against a vulnerable target the test
FAILS (proving the exploit); after a correct fix it PASSES. The test also asserts
the owner's legitimate access still works, so a fix cannot "pass" by breaking the
feature.
"""
from __future__ import annotations

import os
from typing import List

from ..engine.context import AssessmentResult
from ..model.finding import Confidence, Finding

_HEADER = '''"""AUTO-GENERATED by Aegis — access-control regression tests.

Run:  python -m pytest {out_dir}
Each test asserts the SECURE behavior:
  - exploit BEFORE fix  -> FAIL (attacker can read owner's object)
  - exploit AFTER fix   -> PASS (attacker denied; owner still allowed)
"""
import os
import sys

# Make the Aegis package importable regardless of where pytest is invoked.
sys.path.insert(0, {project_root!r})

from aegis.config.scope import load_scope
from aegis.core.evidence import EvidenceLog
from aegis.core.guard import ScopeGuard
from aegis.core.session import SessionManager

SCOPE_FILE = {scope_path!r}


def _login_map():
    scope = load_scope(SCOPE_FILE)
    guard = ScopeGuard(scope)
    evidence = EvidenceLog()
    sessions = SessionManager(scope, guard, evidence)
    idents = {{i.name: i for i in sessions.login_all()}}
    return idents


'''

_TEST = '''
def test_{slug}():
    """{title}"""
    idents = _login_map()
    owner = idents.get({owner!r})
    attacker = idents.get({attacker!r})
    assert owner is not None, "owner identity failed to authenticate"
    assert attacker is not None, "attacker identity failed to authenticate"

    url = {url!r}

    owner_resp = owner.client.get(url)
    assert owner_resp.ok, "regression precondition: owner must still access its own object"

    attacker_resp = attacker.client.get(url)
    disclosed = attacker_resp.ok and attacker_resp.body.strip() == owner_resp.body.strip()
    assert not disclosed, (
        "Broken access control: attacker {attacker!r} retrieved owner {owner!r}'s "
        "object at " + url + " (HTTP %s)" % attacker_resp.status
    )
'''


def _slug(finding: Finding) -> str:
    base = finding.affected.rsplit("/", 2)[-2:]
    raw = "_".join(base) + "_" + finding.fid
    return "".join(c if c.isalnum() else "_" for c in raw).strip("_").lower()


def _parse_owner_attacker(finding: Finding):
    """Recover owner/attacker identity names from the finding reproduction steps."""
    owner = attacker = None
    for step in finding.reproduction:
        if step.startswith("1.") and "as '" in step:
            owner = step.split("as '", 1)[1].split("'", 1)[0]
        if step.startswith("2.") and "user '" in step:
            attacker = step.split("user '", 1)[1].split("'", 1)[0]
    return owner, attacker


def generate_regression_tests(result: AssessmentResult, out_dir: str,
                              scope_path: str, project_root: str) -> List[str]:
    targets = [
        f for f in result.findings
        if f.category == "broken-access-control"
        and f.confidence == Confidence.CONFIRMED
        and f.module == "access_control"
    ]
    if not targets:
        return []

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "test_regressions.py")
    body = [_HEADER.format(out_dir=out_dir, project_root=os.path.abspath(project_root),
                           scope_path=os.path.abspath(scope_path))]
    written = []
    used_slugs = set()
    for f in targets:
        owner, attacker = _parse_owner_attacker(f)
        if not owner or not attacker:
            continue
        slug = _slug(f)
        while slug in used_slugs:
            slug += "_x"
        used_slugs.add(slug)
        body.append(_TEST.format(
            slug=slug,
            title=f.title.replace('"', "'"),
            owner=owner,
            attacker=attacker,
            url=f.affected,
        ))
        f.regression_test = f"test_{slug}"
        written.append(f.regression_test)

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("".join(body))
    return [path] + written
